sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - chromium-chromedriver

language: python

python:
  - 3.6

cache: pip

env:
 - DJANGO_SETTINGS_MODULE=main.settings_test

install:
  - pip install -r requirements_dev.txt

branches:
 only:
  - master

before_script:
  - mkdir logs
  - mkdir media
  - mkdir media/od
  - mkdir media/sounds
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start


script:
  - sleep 3 # give xvfb some time to start
  - python manage.py test
