sudo: required
dist: trusty
addons:
  chrome: stable

language: python

python:
  - 3.6

cache: pip

env:
  - DJANGO_SETTINGS_MODULE=main.settings_test

install:
  - pip install -r requirements_dev.txt

branches:
 only:
  - master

before_script:
  - mkdir logs
  - mkdir media
  - mkdir media/od
  - mkdir media/sounds
  - mkdir driver
  - wget https://chromedriver.storage.googleapis.com/2.43/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d ${HOME}/bin/
  #- ln --symbolic "${HOME}/bin/chromedriver" /usr/bin
  - export PATH=\"${HOME}/bin/"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - sleep 3 # give xvfb some time to start
  - python manage.py test
