sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: python

python:
  - 3.6

cache: pip

env:
 - DJANGO_SETTINGS_MODULE=main.settings_test

install:
  - pip install -r requirements_dev.txt

branches:
 only:
  - master

before_script:
  - mkdir logs
  - mkdir media
  - mkdir media/od
  - mkdir media/sounds

script:
  - xvfb-run --server-args="-screen 0 1024x768x24" make test
  - sleep 3 # give xvfb some time to start
  - python manage.py test
